name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt install mingw-w64 innoextract bison flex texinfo unzip help2man libtool-bin libncurses5-dev libncursesw5-dev

      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - uses: actions/cache@v2
        id: cachetoolchain
        with:
          path: osxcross
          key: ${{ runner.os }}-osxtoolchain

      # Setup osxcross, as detailed here: https://github.com/andrew-d/docker-osxcross/blob/master/Dockerfile
      - name: Setup OSXCross
        if: steps.cachetoolchain.outputs.cache-hit != 'true'
        run: |
          git clone -n https://github.com/tpoechtrager/osxcross.git
          cd osxcross
          git checkout 364703ca0962c4a12688daf8758802a5df9e3221
          sudo apt update
          sudo ./tools/get_dependencies.sh
          curl -L -o ./tarballs/MacOSX10.15.sdk.tar.xz https://github.com/xorrior/osxsdk/raw/master/MacOSX10.15.sdk.tar.xz
          yes | PORTABLE=true ./build.sh
          yes | PORTABLE=true ./build_binutils.sh
      - name: Add OSXCross to path
        run: |
          echo "$GITHUB_WORKSPACE/osxcross/target/bin" >> $GITHUB_PATH

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble -DandroidNdk=/usr/local/lib/android/sdk/ndk-bundle

      - name: Publish
        run: ./gradlew publish -DandroidNdk=/usr/local/lib/android/sdk/ndk-bundle
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          PGP_KEY: ${{ secrets.PGP_KEY }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rapidopus-java/build/libs/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-artifacts
          path: rapidopus-java/build/libs
